### ISSUE TITLE
This is not a issue. It is a feature request and a thank you note

### ISSUE THREAD

**Issue by javanux** [iqbalansari/emacs-emojify#27]
Hey guys thank you so much for such a awesome work and making world a better place :fireworks:   . You guys are great. I use this mode so much with my lovely OS **emacs.** 
 
I was wondering if there is possibilities of adding :heavy_plus_sign: some emojis that are specific to **IT**  stuffs like `git`, `google`, `amazon`, `servers`, `databases`, `emacs`, `router` and so on **......**

**Comment by iqbalansari** [comment]
Hi @javanux,

I am really happy you like the package. As for adding additional emojis, I would love to add them, unfortunately this package depends on [EmojiOne](https://github.com/Ranks/emojione) for emoji images and it does not ship with these images (since these are not yet part of Unicode standard).

However you can always configure `emojify` to display custom emojis. Feel free to ping me if you face issues during the configuration.

Thanks

**Comment by javanux** [comment]
Hey @iqbalansari  thanks for your response. I am trying to customize, but it is not working. I guess `emojify-user-emojis` is not loaded in my emacs or is it different issue? 
![emojify](https://cloud.githubusercontent.com/assets/8892649/21465133/4e764792-c9be-11e6-8382-ddd4fd0ead68.png)

**Comment by iqbalansari** [comment]
Hi,

Thanks for your patience been a bit busy over the last few days.

This is odd, I'd like to think this is because Emacs has not updated the display yet, the emoji should be displayed if force Emacs to redisplay (easiest way to do this is to hit <kbd>RET</kbd> at the first line) 

If the above does not work make sure
- You on latest version of `emojify`
- Emojify mode is enabled

In case the above things look correct, please post the value of the variable `emojify--user-emojis-regexp` after you run the `emojify-set-emoji-data`?

Thanks

**Comment by iqbalansari** [comment]
I guess the above issue has been resolved, closing it. Feel free to re-open if the issue has not been solved yet.

Thanks
