### ISSUE TITLE
Emojis in mode-line

### ISSUE THREAD

**Issue by C0reTex** [iqbalansari/emacs-emojify#29]
First of all, thanks for this great package.
I'm fairly new to Emacs and trying to introduce emoticons to my spaceline on Linux.
Icon support via [spaceline-all-the-icons.el](https://github.com/domtronn/all-the-icons.el/wiki/Spaceline) is no problem and works flawlessly.
At the risk of wasting your time by asking a newbie question, is there a way to make emoticons available in mode-line?

**Comment by iqbalansari** [comment]
Hi,

I am glad you liked the package. I agree that displaying emoticons in `mode-line` would be useful addition, however I do not know how feasible it is, nevertheless I will try to see what can be done once I get some free time

Thanks

**Comment by C0reTex** [comment]
I looked into the code and change log of [mode-icons](https://github.com/ryuslash/mode-icons). It looks like they already make use of your work and are solving this issue in version [0.4](http://projects.ryuslash.org/mode-icons/CHANGELOG.html).

**Comment by iqbalansari** [comment]
Just an update, I got a chance to look into this unfortunately it seems there is no clean way of implementing this such it works with the all the different packages what interact with the mode-line, I need some more time to think about this.

In the meanwhile, is `mode-icons` working for you? I am also trying to create a sort of API that other packages like `mode-icons` can use, instead of fiddling emojify's internals.

**Comment by shackra** [comment]
Any update?

**Comment by C0reTex** [comment]
Sorry for the delay, @iqbalansari . Unfortunately `mode-icons` broke the appearance of my spaceline. To solve this issue I replaced it by  [all-the-icons](https://github.com/domtronn/all-the-icons.el/wiki/Mode-Line) as long as I am writing my thesis.

**Comment by iqbalansari** [comment]
Hey,

Sorry for the delay in the replying, @C0reTex and @shackra, I was away on a vacation.

I have implemented some basic support for displaying emojis in mode-line on the latest master. Since this is an experimental feature you need to explicitly enable it by enabling the `emojify-mode-line-mode` (to enable it globally for all buffers use `global-emojify-mode-line-mode`). Once I am sure of this feature, I will enable it by default.

@C0reTex Since you mentioned you use `spaceline` make sure you call `emojify-mode-line-mode`/ `global-emojify-mode-line-mode` **after** you enable `spaceline`

Needless to say, since this is a new feature, it might have some bugs, feel free to report them.

Thanks

**Comment by iqbalansari** [comment]
Closing this since the support has been added on master
