### ISSUE TITLE
Not working in org-mode.

### ISSUE THREAD

**Issue by dwrz** [iqbalansari/emacs-emojify#30]
On Emacs 25.2.1, running on Arch Linux x86_64, I can't get emojis to display in org-mode.

Emojify works fine in message mode and Lisp Interaction (scratch). Listing the emojis also displays them. In org-mode, however, I'm only getting the unicode character. This is even after I try to enable/disable emojify-mode.

Strangely enough, org-bullet-mode, which I don't regularly use, also seems to work fine when enabled.

Update: after installing Symbola, some emoji's appear to be displaying in org-mode. I'm not sure why that's the case.

**Comment by iqbalansari** [comment]
Hi,

Thanks for the bug report and sorry for the delay in replying. 

There are some places in org-mode where `emojify` does not display since it could be potentially annoying. For example displaying "8)" as 😎 would be annoying if I am in an org-mode list. Perhaps you are hitting such a case. I think there some scope to make the heuristics smarter.

Could you please post the a minimal `org-mode` text that is not working as expected?

Thanks

**Comment by dwrz** [comment]
```
*** 20170708
**** log                                                                :log:
     :PROPERTIES:
     :NOTES:
     :END:
     :LOGBOOK:
     - Added [2017-07-08 Sat 12:50].
     :END:
- [2017-07-08 Sat 12:51] - Test (🍅🦑).
```

Before I installed Symbola, neither icon would show up. Now the tomato does, but not the squid (even though the squid shows up in my browser). Note that the tomato, is in Symbola (black and white) -- not a colored emoji.

Thanks for your time and help!

**Comment by iqbalansari** [comment]
I have pushed some commits which should fix the display of emojis in org-mode, could you it once MELPA builds the new version and report back

Thanks

**Comment by dwrz** [comment]
It's working -- thank you!
