### ISSUE TITLE
electric backspace

### ISSUE THREAD

**Issue by ryanprior** [iqbalansari/emacs-emojify#5]
If you see an emoji, you don't necessarily know how many backspaces it'll take to delete it. Could be just one for a Unicode emoji or many for a github-style one. We can eliminate this uncertainty by advising delete to remove the whole emoji, regardless of how many literal characters it contains.

**Comment by iqbalansari** [comment]
This sounds like a useful feature. I will work on this once the existing bugs are resolved. 

In terms of implementation I think advising delete would be tricky since there are multiple ways in which text can be deleted (one example in `sp-delete-char`) perhaps we can simply advice `delete-char` but advises can be tricky as such I try to avoid them if possible. 

One approach would be to add a [local keymap](http://www.gnu.org/software/emacs/manual/html_node/elisp/Special-Properties.html#Special-Properties) for emoji text.

**Comment by iqbalansari** [comment]
Hi,

I have implemented this on master. Please give it a try when MELPA builds.
