### ISSUE TITLE
multiple emoji in sequence

### ISSUE THREAD

**Issue by ryanprior** [iqbalansari/emacs-emojify#6]
":100: 😄" is converted into two emojis, but ":100:😄" with no whitespace between is left untouched. Similarly, ":100:abcdef😄" is left untouched. The desired behavior should convert to emojis in all these cases.

**Comment by iqbalansari** [comment]
That is because the package is very [conservative](https://github.com/iqbalansari/emacs-emojify/blob/e23e1e43f1642f9bbd216849f42bd45b1f0e9434/emojify.el#L356-L389) about displaying emojis. This was done mainly to avoid cases where plain ascii emojis can appear in a word for example `d:` in `head:`. Thinking about it again I think it is very restrictive perhaps we can do those checks only for `ascii` emojis. What do you think?

**Comment by ryanprior** [comment]
If it was me, I would turn off ASCII emojis by default. Only in certain contexts (chatrooms or twittering-mode, for example) would I be tempted to turn them on. Otherwise emojifying them just isn't that useful, as they're pretty much homoiconic. We might offer something in the customize interface that lets you set styles depending on the mode.

For github-style emojis, it's a slightly harder call. For example, if you're trying to write a colon-separated list like `lang=de:us:se:es:jp` but emojify turns that into lang=de:us:se:es:jp, then that's maybe annoying. But the cases like that you run into are going to be few compared to the ASCII style.

For unicode emojis, I don't see any benefit to being conservative. We can afford to aggressively emojify those.

**Comment by iqbalansari** [comment]
Should be better on latest master. Please do report back if it works properly or if you face any additional issues. Thanks

**Comment by iqbalansari** [comment]
Hi,

I am closing this. Please feel free to open further issues if you face any problems.

Thanks
