### ISSUE TITLE
Org-mode tags converting to emoji

### ISSUE THREAD

**Issue by wakatara** [iqbalansari/emacs-emojify#68]
If you are a heavy use of tags in org-mode in emacs, emacs-emojify uses the `:books:` and similar tags and converts them inline to a graphic. I actually was puzzled the first time it happened until I realized it was a book emoji... =] 

In any case, is there a way to avoid that? While it made my tags much more exciting it is a bit distracting in programs that take the tags and display them in summaries (eg. Deft etc.). 

btw, I really do love this package. Thank you for your work on it. It makes emacs much much nicer.

**Comment by iqbalansari** [comment]
Hello @wakatara, thanks for the bug report, by default `emojify` does not display org-tags as emojis, but there was a bug in the regex it used to detect the tags. I have pushed a fix for this on master. I have also disabled the display of emojis in `deft-mode`, since the regex fix does not apply in case of `deft-mode` as the context there is different.

Could you try once MELPA builds the new version and let me know if it fixes your issue?

**Comment by wakatara** [comment]
Appears to be fixed.
